### ISSUE TITLE
PHP and data-remote

### ISSUE THREAD

**Issue by FL20161** [1000hz/validator-remote-example#1]
Hi,

as we can see in the documentation : data-remote="/path/to/remote/validator?<name>=<value>"
Is it possible to have a php file to validate ? for instance : data-remote="includes/emailvalidator.php" 

We could get the variable with a $_GET['email'] to check into a mysql database if the email already exists.

My question is : What could i use to send the answer of my php code after validation (200 and 400) ? 
i tried : "http_response_code(200);" but it doesn't work

thanks and regards

**Comment by 1000hz** [comment]
> Is it possible to have a php file to validate ? for instance : data-remote="includes/emailvalidator.php

Yes

> We could get the variable with a $_GET['email'] to check into a mysql database if the email already exists.

Yes, assuming that your input field is `name="email"`

> My question is : What could i use to send the answer of my php code after validation (200 and 400) ? 
> i tried : "http_response_code(200);" but it doesn't work

If the validator receives a 200 it will mark the field as valid. If 400, it will mark it as invalid. Inspect the request/response in your browser console (via Chrome's dev tools) to verify everything is being sent and received as expected.

**Comment by 1000hz** [comment]
assuming your input is as follows `<input name="email" data-remote="includes/emailvalidator.php">`

Then you should expect to see a GET request to `http://your.domain/your/current/path/includes/emailvalidator.php?email=FIELDVALUE`

**Comment by FL20161** [comment]
thanks for your answer, actually i had a problem with the http_response_code()

so i created this function : 

<?php
if (!function_exists('http_response_code'))
{
    function http_response_code($newcode = NULL)
    {
        static $code = 200;
        if($newcode !== NULL)
        {
            header('X-PHP-Response-Code: '.$newcode, true, $newcode);
            if(!headers_sent())
                $code = $newcode;
        }  
        return $code;
    }
}

and now it works really well, thanks for your help
