### ISSUE TITLE
jquery issue?

### ISSUE THREAD

**Issue by mochsner** [1000hz/validator-remote-example#2]
Getting a 404 error for the following jquery request:

xhr.send( options.hasContent && options.data || null );

**Comment by 1000hz** [comment]
That’s not code from this library. You’re probably not using the right one.
This is `bootstrap-validator`.

**Comment by mochsner** [comment]
My apologies - don't even know where I was actually supposed to open the issue I was facing. I'll try to open a ticket to remove it, but I know it's a pain & it may not go through... sorry again
